//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XHTD_SERVICES.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public System.Guid Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Unit_Code { get; set; }
        public string Unit_Name { get; set; }
        public string Type_Code { get; set; }
        public string Type_Name { get; set; }
        public string UnitCode { get; set; }
        public string TypeCode { get; set; }
        public Nullable<double> CostPrice { get; set; }
        public Nullable<double> SellPrice { get; set; }
        public Nullable<double> Proportion { get; set; }
        public Nullable<double> PercentageOfImpurities { get; set; }
        public Nullable<bool> IsMainObject { get; set; }
        public Nullable<bool> IsQuantitative { get; set; }
        public Nullable<double> Cement { get; set; }
        public Nullable<double> Stone { get; set; }
        public Nullable<double> Sand { get; set; }
        public Nullable<double> Admixture { get; set; }
        public Nullable<double> Water { get; set; }
        public Nullable<System.Guid> ItemFormula_Id { get; set; }
    
        public virtual ItemFormula ItemFormula { get; set; }
    }
}
