//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XHTD_SERVICES.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCallToGatewayConfig
    {
        public int Id { get; set; }
        public Nullable<int> ExportPlanId { get; set; }
        public string ExportPlanName { get; set; }
        public Nullable<int> MaxVehiclePcb30 { get; set; }
        public Nullable<int> MaxVehiclePcb40 { get; set; }
        public Nullable<int> MaxVehicleC91 { get; set; }
        public Nullable<int> MaxVehicleJumbo { get; set; }
        public Nullable<int> MaxVehicleSling { get; set; }
        public Nullable<int> MaxVehicleRoi { get; set; }
        public Nullable<int> MaxVehicleClinker { get; set; }
        public Nullable<int> MaxVehicleOther { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> SourceDocumentId { get; set; }
        public string SourceDocumentName { get; set; }
    }
}
