//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XHTD_SERVICES.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDriver
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public System.DateTime Birthday { get; set; }
        public string Gender { get; set; }
        public string IdCard { get; set; }
        public string Address { get; set; }
        public string UserName { get; set; }
        public bool State { get; set; }
        public System.DateTime CreateDay { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime UpdateDay { get; set; }
        public string UpdateBy { get; set; }
    }
}
