//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XHTD_SERVICES.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblExportPlanDetail
    {
        public int Id { get; set; }
        public int PlanId { get; set; }
        public int ProductIdSyn { get; set; }
        public string ProductName { get; set; }
        public int DistributorIdSyn { get; set; }
        public string DistributorName { get; set; }
        public int AreaId { get; set; }
        public string AreaName { get; set; }
        public Nullable<double> OrderNumber { get; set; }
        public Nullable<System.DateTime> LimitFromDate { get; set; }
        public Nullable<double> LimitNumber { get; set; }
        public Nullable<System.DateTime> LimitToDate { get; set; }
    
        public virtual tblExportPlan tblExportPlan { get; set; }
    }
}
