//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XHTD_SERVICES.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMachineTrough
    {
        public int Id { get; set; }
        public string MachineCode { get; set; }
        public string TroughCode { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual tblMachine tblMachine { get; set; }
        public virtual tblTrough tblTrough { get; set; }
    }
}
