//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XHTD_SERVICES.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPrint
    {
        public int Id { get; set; }
        public string DeliveryCode { get; set; }
        public string InvoiceNo { get; set; }
        public string Status { get; set; }
        public string ErpOrderId { get; set; }
    }
}
