//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XHTD_SERVICES.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblQualityCertificateCCCL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblQualityCertificateCCCL()
        {
            this.TblQualityCertificateCCCLProcesses = new HashSet<TblQualityCertificateCCCLProcess>();
            this.tblStoreOrderOperatings = new HashSet<tblStoreOrderOperating>();
            this.TblQualityCertificates = new HashSet<TblQualityCertificate>();
        }
    
        public string Code { get; set; }
        public string Name { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public string State { get; set; }
        public string Note { get; set; }
        public string Source { get; set; }
        public Nullable<System.DateTime> CreateDay { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateDay { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.Guid> ReferenceId { get; set; }
        public Nullable<System.Guid> TempReferenceId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblQualityCertificateCCCLProcess> TblQualityCertificateCCCLProcesses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStoreOrderOperating> tblStoreOrderOperatings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblQualityCertificate> TblQualityCertificates { get; set; }
    }
}
