//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XHTD_SERVICES.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStoreOrderOperatingHistory
    {
        public int Id { get; set; }
        public string DeliveryCode { get; set; }
        public string Vehicle { get; set; }
        public string TypeProduct { get; set; }
        public Nullable<decimal> SumNumber { get; set; }
        public string NameDistributor { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string LogChange { get; set; }
        public Nullable<System.DateTime> TimeChange { get; set; }
    }
}
