//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XHTD_SERVICES.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSendTroughStatu
    {
        public string MachineCode { get; set; }
        public string TroughCode { get; set; }
        public string DeliveryCode { get; set; }
        public string Vehicle { get; set; }
        public string BookQuantity { get; set; }
        public string LocationCodeTgc { get; set; }
        public bool IsSent { get; set; }
        public int Id { get; set; }
        public Nullable<bool> IsSentStart { get; set; }
        public Nullable<bool> IsSentStop { get; set; }
    }
}
