//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XHTD_SERVICES.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTypeProductCallToGatewayConfig
    {
        public int Id { get; set; }
        public string TypeProductCode { get; set; }
        public Nullable<int> MaxVehicleNumber { get; set; }
        public Nullable<int> CallToGatewayConfigId { get; set; }
    
        public virtual tblCallToGatewayConfig tblCallToGatewayConfig { get; set; }
    }
}
