//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XHTD_SERVICES.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVehicle
    {
        public int IDVehicle { get; set; }
        public int IDStore { get; set; }
        public string Vehicle { get; set; }
        public double Tonnage { get; set; }
        public double TonnageDefault { get; set; }
        public string NameDriver { get; set; }
        public string IdCardNumber { get; set; }
        public string HeightVehicle { get; set; }
        public string WidthVehicle { get; set; }
        public string LongVehicle { get; set; }
        public System.DateTime DayCreate { get; set; }
        public System.DateTime DayUpdate { get; set; }
        public string UserCreate { get; set; }
        public string UserUpdate { get; set; }
        public int UnladenWeight1 { get; set; }
        public int UnladenWeight2 { get; set; }
        public int UnladenWeight3 { get; set; }
        public bool IsSetMediumUnladenWeight { get; set; }
        public System.DateTime CreateDay { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime UpdateDay { get; set; }
        public string UpdateBy { get; set; }
    }
}
